spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        
logging:
  level:
    com.example.store: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Redis configuration for development
spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms
  cache:
    redis:
      time-to-live: 600000 # 10 minutes in dev for faster testing
      cache-null-values: false

# Cache management enabled in development
app:
  cache:
    management:
      enabled: true