# Kubernetes Secrets Template
# DO NOT commit actual secrets to version control
# Use this template to create your secrets with real values

apiVersion: v1
kind: Secret
metadata:
  name: store-app-secrets
  namespace: store-app
  labels:
    app.kubernetes.io/name: store-app
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Base64 encoded values - use: echo -n 'your-value' | base64
  # Example: echo -n 'jdbc:postgresql://postgres:5432/store_db' | base64
  database-url: <BASE64_ENCODED_DATABASE_URL>
  database-username: <BASE64_ENCODED_DATABASE_USERNAME>
  database-password: <BASE64_ENCODED_DATABASE_PASSWORD>
  redis-password: <BASE64_ENCODED_REDIS_PASSWORD>

---
# Docker Registry Secret for pulling images from GitHub Container Registry
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: store-app
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <BASE64_ENCODED_DOCKER_CONFIG>

# To create the Docker config secret:
# kubectl create secret docker-registry ghcr-secret \
#   --docker-server=ghcr.io \
#   --docker-username=<GITHUB_USERNAME> \
#   --docker-password=<GITHUB_TOKEN> \
#   --docker-email=<EMAIL> \
#   --namespace=store-app