apiVersion: v1
kind: ServiceAccount
metadata:
  name: store-app
  namespace: store-app
  labels:
    app.kubernetes.io/name: store-app
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: store-application
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: store-app
  name: store-app-role
  labels:
    app.kubernetes.io/name: store-app
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: store-app-rolebinding
  namespace: store-app
  labels:
    app.kubernetes.io/name: store-app
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: rbac
subjects:
- kind: ServiceAccount
  name: store-app
  namespace: store-app
roleRef:
  kind: Role
  name: store-app-role
  apiGroup: rbac.authorization.k8s.io