apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: store-app-servicemonitor
  namespace: store-app
  labels:
    app.kubernetes.io/name: store-app
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: store-application
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: store-app
      app.kubernetes.io/instance: production
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
    scrapeTimeout: 10s
    honorLabels: true
  namespaceSelector:
    matchNames:
    - store-app