name: Dependency Security Check

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:
  push:
    paths:
      - 'build.gradle'
      - 'gradle/**'

jobs:
  dependency-check:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'eclipse-temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run dependency check
      run: ./gradlew dependencyCheckAnalyze

    - name: Upload dependency check results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dependency-check-report
        path: build/reports/dependency-check-report.html

    - name: Create security issue on vulnerabilities
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const { data: issues } = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            labels: 'security,dependencies'
          });
          
          if (issues.length === 0) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Security vulnerabilities detected in dependencies',
              body: `## 🔒 Dependency Security Alert
              
              The automated dependency check has detected security vulnerabilities in project dependencies.
              
              ### Action Required:
              1. Review the dependency check report in the workflow artifacts
              2. Update vulnerable dependencies to secure versions
              3. Test the application after updates
              4. Close this issue once resolved
              
              **Workflow Run:** [View Details](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})
              
              This issue was automatically created by the dependency security check workflow.`,
              labels: ['security', 'dependencies', 'automated']
            });
          }